# Generated by Django 5.0.6 on 2024-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizzatore',
            name='immagine_profilo',
            field=models.ImageField(blank=True, default='static\\images\\defaults\\default_user.png', upload_to='images/organizers'),
        ),
        migrations.AddField(
            model_name='utente',
            name='immagine_profilo',
            field=models.ImageField(blank=True, default='static\\images\\defaults\\default_user.png', null=True, upload_to='images/customers'),
        ),
    ]
