# Generated by Django 5.0.6 on 2024-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_organizzatore_immagine_profilo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizzatore',
            name='immagine_profilo',
            field=models.ImageField(blank=True, default='static\\images\\defaults\\default_user.jpg', upload_to='images/organizers'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='immagine_profilo',
            field=models.ImageField(blank=True, default='static\\images\\defaults\\default_user.jpg', null=True, upload_to='images/customers'),
        ),
    ]
