# Generated by Django 5.0.6 on 2024-07-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_organizzatore_immagine_profilo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizzatore',
            name='notifiche',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='notifiche',
        ),
    ]
