# Generated by Django 5.0.6 on 2024-07-11 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_organizzatore_notifiche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='carta_credito',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='indirizzo',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='scadenza_carta',
        ),
        migrations.AlterField(
            model_name='organizzatore',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organizzatore',
            name='immagine_profilo',
            field=models.ImageField(blank=True, upload_to='images/organizers'),
        ),
        migrations.AlterField(
            model_name='organizzatore',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizzatore',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='cognome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utente',
            name='data_nascita',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utente',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='immagine_profilo',
            field=models.ImageField(blank=True, upload_to='images/customers'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='utente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('Altro', 'Altro'), ('Maschio', 'Maschio'), ('Femmina', 'Femmina')], default='Altro', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='stato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
