# Generated by Django 5.0.6 on 2024-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_organizzatore_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizzatore',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='organizzatori_preferiti', to='users.utente'),
        ),
    ]
