# Generated by Django 5.0.6 on 2024-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(max_length=255)),
                ('capienza_persone', models.PositiveIntegerField()),
                ('citta', models.CharField(max_length=100)),
                ('stato', models.CharField(max_length=100)),
                ('codice_postale', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Luoghi',
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=50)),
                ('data_ora', models.DateTimeField(default='16/05/2024 21:30:29')),
            ],
            options={
                'verbose_name_plural': 'Notifiche',
            },
        ),
    ]
