# Generated by Django 5.0.6 on 2024-07-04 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_ordine_data_ora'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('indirizzo', models.CharField(max_length=255)),
                ('capienza_persone', models.PositiveIntegerField()),
                ('citta', models.CharField(max_length=100)),
                ('stato', models.CharField(max_length=100)),
                ('codice_postale', models.CharField(max_length=30)),
                ('affittuari', models.ManyToManyField(blank=True, default=None, related_name='luoghi_affittati', to='users.organizzatore')),
                ('followers', models.ManyToManyField(blank=True, default=None, related_name='luoghi_preferiti', to='users.utente')),
            ],
            options={
                'verbose_name_plural': 'Luoghi',
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=50)),
                ('data_ora', models.DateTimeField(default='04/07/2024 23:53:13')),
                ('luogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_luogo', to='common.luogo')),
                ('ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_ordine', to='orders.ordine')),
                ('organizzatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_organizzatore', to='users.organizzatore')),
            ],
            options={
                'verbose_name_plural': 'Notifiche',
            },
        ),
    ]
