# Generated by Django 5.0.6 on 2024-05-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('orders', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifica',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_evento', to='sellers.evento'),
        ),
        migrations.AddField(
            model_name='notifica',
            name='luogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_luogo', to='common.luogo'),
        ),
        migrations.AddField(
            model_name='notifica',
            name='ordine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_ordine', to='orders.ordine'),
        ),
        migrations.AddField(
            model_name='notifica',
            name='organizzatore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_organizzatore', to='sellers.organizzatore'),
        ),
    ]
