# Generated by Django 5.0.6 on 2024-07-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifica',
            name='data_ora',
            field=models.DateTimeField(default='04/07/2024 23:53:20'),
        ),
    ]
