# Generated by Django 5.0.6 on 2024-06-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifica',
            name='data_ora',
            field=models.DateTimeField(default='03/06/2024 00:20:17'),
        ),
    ]
