# Generated by Django 5.0.6 on 2024-07-05 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_notifica_data_ora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifica',
            name='data_ora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
