# Generated by Django 5.0.6 on 2024-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_notifica_data_ora'),
    ]

    operations = [
        migrations.AddField(
            model_name='luogo',
            name='immagine',
            field=models.ImageField(blank=True, default='static\\images\\defaults\\default_venue.png', upload_to='images/venues'),
        ),
    ]
