# Generated by Django 5.0.6 on 2024-07-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_luogo_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luogo',
            name='immagine',
            field=models.ImageField(blank=True, default='images/defaults/default_venue.jpg', upload_to='images/venues'),
        ),
    ]
