# Generated by Django 5.0.6 on 2024-07-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_notifica_letta'),
        ('products', '0006_alter_evento_locandina'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifica',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_evento', to='products.evento'),
        ),
    ]
