# Generated by Django 5.0.6 on 2024-07-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_notifica_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luogo',
            name='codice_postale',
        ),
        migrations.RemoveField(
            model_name='luogo',
            name='stato',
        ),
    ]
