# Generated by Django 5.0.6 on 2024-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_luogo_codice_postale_remove_luogo_stato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luogo',
            name='immagine',
            field=models.ImageField(blank=True, upload_to='images/venues'),
        ),
    ]
