# Generated by Django 5.0.6 on 2024-07-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_luogo_immagine'),
        ('users', '0008_alter_organizzatore_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luogo',
            name='affittuari',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='luoghi_affittati', to='users.organizzatore'),
        ),
        migrations.AlterField(
            model_name='luogo',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='luoghi_preferiti', to='users.utente'),
        ),
        migrations.AlterField(
            model_name='luogo',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/venues'),
        ),
    ]
