# Generated by Django 5.0.6 on 2024-05-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizzatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, default='', null=True)),
                ('notifiche', models.BooleanField(default=False)),
                ('luoghi_affittati', models.ManyToManyField(blank=True, default=None, related_name='affittuari', to='common.luogo')),
            ],
            options={
                'verbose_name_plural': 'Organizzatori',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, default='', null=True)),
                ('data_ora', models.DateTimeField(default='16/05/2024 21:30:29')),
                ('categoria', models.CharField(max_length=100)),
                ('luogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventi_programmati', to='common.luogo')),
                ('organizzatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventi_organizzati', to='sellers.organizzatore')),
            ],
            options={
                'verbose_name_plural': 'Eventi',
            },
        ),
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=100)),
                ('prezzo', models.FloatField(default=0.0)),
                ('descrizione', models.TextField(blank=True, default='', null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biglietti_disponibili', to='sellers.evento')),
                ('organizzatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biglietti_generati', to='sellers.organizzatore')),
            ],
            options={
                'verbose_name_plural': 'Biglietti',
            },
        ),
    ]
