# Generated by Django 5.0.6 on 2024-05-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default='16/05/2024 21:31:06'),
        ),
    ]
