# Generated by Django 5.0.6 on 2024-05-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_evento_data_ora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biglietto',
            name='prezzo',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='biglietto',
            name='tipologia',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default='16/05/2024 22:23:34'),
        ),
    ]
