# Generated by Django 5.0.6 on 2024-05-16 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascita', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('Altro', 'Altro')], default='Altro', max_length=10, null=True)),
                ('stato', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('carta_credito', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('cvv', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('scadenza_carta', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('notifiche', models.BooleanField(default=False)),
                ('eventi_preferiti', models.ManyToManyField(blank=True, default=None, related_name='followers', to='sellers.evento')),
                ('luoghi_preferiti', models.ManyToManyField(blank=True, default=None, related_name='followers', to='common.luogo')),
                ('organizzatori_preferiti', models.ManyToManyField(blank=True, default=None, related_name='followers', to='sellers.organizzatore')),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
    ]
