# Generated by Django 5.0.6 on 2024-06-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(default='12/06/2024 21:17:26')),
                ('totale', models.FloatField(default=0.0)),
                ('organizzatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='users.organizzatore')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='users.utente')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
            },
        ),
    ]
