# Generated by Django 5.0.6 on 2024-05-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(default='16/05/2024 21:30:29')),
                ('totale', models.FloatField(default=0.0)),
                ('biglietti', models.ManyToManyField(blank=True, default=None, related_name='ordini', to='sellers.biglietto')),
                ('organizzatore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='sellers.organizzatore')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='customers.utente')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
            },
        ),
    ]
