# Generated by Django 5.0.6 on 2024-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ora',
            field=models.DateTimeField(default='16/05/2024 21:30:59'),
        ),
    ]
