# Generated by Django 5.0.6 on 2024-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordine_data_ora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ora',
            field=models.DateTimeField(default='12/06/2024 18:53:38'),
        ),
    ]
