# Generated by Django 5.0.6 on 2024-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordine_data_ora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='data_ora',
            field=models.DateTimeField(default='28/06/2024 18:45:19'),
        ),
    ]
