# Generated by Django 5.0.6 on 2024-07-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_ordine_data_ora'),
        ('products', '0006_alter_evento_locandina'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='biglietti',
            field=models.ManyToManyField(related_name='ordini', to='products.biglietto'),
        ),
    ]
