# Generated by Django 5.0.6 on 2024-07-09 16:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordine_biglietti'),
        ('products', '0006_alter_evento_locandina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='biglietti',
        ),
        migrations.CreateModel(
            name='BigliettoAcquistato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acquirente', models.CharField(max_length=100)),
                ('cognome_acquirente', models.CharField(max_length=100)),
                ('data_acquisto', models.DateTimeField(default=django.utils.timezone.now)),
                ('biglietto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biglietti_acquistati', to='products.biglietto')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biglietti_acquistati', to='orders.ordine')),
            ],
        ),
    ]
