# Generated by Django 5.0.6 on 2024-07-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_ordine_biglietti_bigliettoacquistato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigliettoacquistato',
            options={'verbose_name_plural': 'Biglietti Acquistati'},
        ),
    ]
