# Generated by Django 5.0.6 on 2024-07-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_bigliettoacquistato_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigliettoacquistato',
            name='cognome_acquirente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bigliettoacquistato',
            name='nome_acquirente',
            field=models.CharField(max_length=50),
        ),
    ]
