# Generated by Django 5.0.6 on 2024-07-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_bigliettoacquistato_biglietto'),
        ('products', '0010_alter_evento_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigliettoacquistato',
            name='biglietto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biglietti_acquistati', to='products.biglietto'),
        ),
    ]
