# Generated by Django 5.0.6 on 2024-07-16 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_bigliettoacquistato_biglietto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigliettoacquistato',
            name='data_nascita_acquirente',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bigliettoacquistato',
            name='sesso_acquirente',
            field=models.CharField(blank=True, choices=[('Altro', 'Altro'), ('Maschio', 'Maschio'), ('Femmina', 'Femmina')], default='Altro', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bigliettoacquistato',
            name='stato_acquirente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
