# Generated by Django 5.0.6 on 2024-07-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_bigliettoacquistato_data_nascita_acquirente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigliettoacquistato',
            name='sesso_acquirente',
            field=models.CharField(choices=[('Altro', 'Altro'), ('Maschio', 'Maschio'), ('Femmina', 'Femmina')], default='Altro', max_length=10),
        ),
        migrations.AlterField(
            model_name='bigliettoacquistato',
            name='stato_acquirente',
            field=models.CharField(max_length=50),
        ),
    ]
