# Generated by Django 5.0.6 on 2024-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_bigliettoacquistato_sesso_acquirente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigliettoacquistato',
            name='prezzo_acquisto',
            field=models.FloatField(default=0.0),
        ),
    ]
