# Generated by Django 5.0.6 on 2024-07-05 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Concerti', 'Concerti'), ('Festival', 'Festival'), ('Teatro', 'Teatro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
