# Generated by Django 5.0.6 on 2024-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Concerto', 'Concerto'), ('Festival', 'Festival'), ('Teatro', 'Teatro')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default='28/06/2024 18:45:19'),
        ),
    ]
