# Generated by Django 5.0.6 on 2024-06-28 22:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_notifica_data_ora'),
        ('products', '0002_alter_evento_categoria_alter_evento_data_ora'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Concerto', 'Concerto'), ('Festival', 'Festival'), ('Teatro', 'Teatro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 0, 41, 52, 820168)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='luogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_programmati', to='common.luogo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizzatore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_organizzati', to='users.organizzatore'),
        ),
    ]
