# Generated by Django 5.0.6 on 2024-06-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_evento_data_ora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default='05/06/2024 00:39:57'),
        ),
    ]
