# Generated by Django 5.0.6 on 2024-07-03 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_evento_data_ora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 0, 58, 47, 499092)),
        ),
    ]
