# Generated by Django 5.0.6 on 2024-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_evento_locandina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='locandina',
            field=models.ImageField(blank=True, default='static\\images\\defaults\\default_event.jpg', upload_to='images/events'),
        ),
    ]
