# Generated by Django 5.0.6 on 2024-06-29 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_evento_categoria_alter_evento_data_ora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biglietto',
            name='disponibilita',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 10, 10, 2, 989133)),
        ),
    ]
