# Generated by Django 5.0.6 on 2024-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_evento_data_ora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default='06/06/2024 15:43:08'),
        ),
    ]
