# Generated by Django 5.0.6 on 2024-07-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_evento_locandina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='locandina',
            field=models.ImageField(blank=True, upload_to='images/events'),
        ),
    ]
