# Generated by Django 5.0.6 on 2024-07-01 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_biglietto_disponibilita_biglietto_quantita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biglietto',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 23, 18, 15, 232865)),
        ),
    ]
