# Generated by Django 5.0.6 on 2024-07-01 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_biglietto_slug_alter_evento_data_ora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_ora',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 23, 18, 27, 421144)),
        ),
    ]
