# Generated by Django 5.0.6 on 2024-07-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_evento_locandina'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='visualizzazioni',
            field=models.IntegerField(default=0),
        ),
    ]
