# Generated by Django 5.0.6 on 2024-07-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_evento_visualizzazioni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biglietto',
            name='prezzo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='biglietto',
            name='tipologia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='visualizzazioni',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
