# Generated by Django 5.0.6 on 2024-07-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_biglietto_prezzo_alter_biglietto_tipologia_and_more'),
        ('users', '0008_alter_organizzatore_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biglietto',
            name='ordine',
        ),
        migrations.AlterField(
            model_name='biglietto',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='eventi_preferiti', to='users.utente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='locandina',
            field=models.ImageField(blank=True, null=True, upload_to='images/events'),
        ),
    ]
