# Generated by Django 5.0.6 on 2024-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_evento_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='biglietto',
            name='quantita_vendibile',
            field=models.IntegerField(default=0),
        ),
    ]
